// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqxXV9B7YaDilkFH-2hcR8McpAXHCZFiI',
    appId: '1:787627255680:web:d1d8ec214d3d2254f60365',
    messagingSenderId: '787627255680',
    projectId: 'solarweb-f7f4c',
    authDomain: 'solarweb-f7f4c.firebaseapp.com',
    storageBucket: 'solarweb-f7f4c.appspot.com',
    measurementId: 'G-RMJ6GM5FJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnGFtacDwegae6BluIUByzyE6TGi5NiKY',
    appId: '1:787627255680:android:b65bd2d4a76d9dfaf60365',
    messagingSenderId: '787627255680',
    projectId: 'solarweb-f7f4c',
    storageBucket: 'solarweb-f7f4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJvgrsUEr70MToJq1Wm-KvUSHPir44cvg',
    appId: '1:787627255680:ios:f465db8909dc5ad6f60365',
    messagingSenderId: '787627255680',
    projectId: 'solarweb-f7f4c',
    storageBucket: 'solarweb-f7f4c.appspot.com',
    iosClientId: '787627255680-11teo33lmhatjeefogptvibv39n3vvr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.solarWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJvgrsUEr70MToJq1Wm-KvUSHPir44cvg',
    appId: '1:787627255680:ios:f465db8909dc5ad6f60365',
    messagingSenderId: '787627255680',
    projectId: 'solarweb-f7f4c',
    storageBucket: 'solarweb-f7f4c.appspot.com',
    iosClientId: '787627255680-11teo33lmhatjeefogptvibv39n3vvr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.solarWeb',
  );
}
